modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/ScarlettShooter/hier/issues" #optional
[[mods]] #mandatory
modId="hier" #mandatory
version="${file.jarVersion}" #mandatory
displayName="High Energistics Reborn" #mandatory
updateJSONURL="" #optional
displayURL="https://github.com/ScarlettShooter/hier" #optional
logoFile="" #optional
credits="Thanks to Forge Team, McJTY and me :D" #optional
authors="ScarlettShooter" #optional
description='''
Some description?
'''
[[dependencies.hier]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.hier]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
